// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvyavzjzdinelcufpzek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12eWF2emp6ZGluZWxjdWZwemVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NDU1ODcsImV4cCI6MjA2OTUyMTU4N30.ooo-nyhz_Tr0TjvLeU3Y8s-OtMDW4K6OiF04i5vAPAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});